export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_PANTRY_ITEMS = "FETCH_PANTRY_ITEMS";
export const SET_PANTRY_ITEMS = "SET_PANTRY_ITEMS";
export const ADD_PANTRY_ITEM = "ADD_PANTRY_ITEM";
export const REMOVE_PANTRY_ITEM = "REMOVE_PANTRY_ITEM";
export const UPDATE_PANTRY_ITEM = "UPDATE_PANTRY_ITEM";
export const EDIT_PANTRY_ITEM = "EDIT_PANTRY_ITEM";
export const HIGHLIGHT_ITEMS = "HIGHLIGHT_ITEMS";
export const REMOVE_HIGHLIGHTS = "REMOVE_HIGHLIGHTS";

export const FETCH_RECIPES = "FETCH_RECIPES";
export const SET_RECIPES = "SET_RECIPES";
export const ADD_RECIPE = "ADD_RECIPE";
export const REMOVE_RECIPE = "REMOVE_RECIPE";
export const HOVER_RECIPE = "HOVER_RECIPE";
export const UPDATE_RECIPE = "UPDATE_RECIPE";
export const EDIT_RECIPE = "EDIT_RECIPE";
export const FINISH_EDIT = "FINISH_EDIT";

export const FETCH_FAILURE = "FETCH_FAILURE";
